# Change these first
owner: opensourcepos # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Demo
    url: https://demo.opensourcepos.org
  - name: System
    url: https://dev.opensourcepos.org
  - name: Translate
    url: https://translate.opensourcepos.org
 

status-website:

  cname: status.opensourcepos.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Mafindo System Monitor"
  introMessage: This page shows **real-time** deploy stats for our test and dev servers.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://kreasiindo.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
